#!/usr/bin/env python3
# sdn_campus_topo_v6.py - CT/2020/087 R.M.K.K.Siriwardhana
# Reusable SDN medium campus topology. Structural mirror of
# traditional_campus_topo_v4.py; only the paradigm differs (Ryu + OpenFlow).

import os
import re
import time
from statistics import mean

from mininet.net import Mininet
from mininet.node import OVSSwitch, RemoteController
from mininet.link import TCLink
from mininet.log import setLogLevel, info
from mininet.cli import CLI

# Link bandwidth caps (Mbps). TCLink + bw= enforces real shaping via Linux tc;
# a plain Link has no limit and gives meaningless multi Gbps numbers.
BW_CORE_CORE  = 1000
BW_CORE_AREA  = 1000
BW_AREA_DIST  = 1000
BW_DIST_ACC   = 1000
BW_ACC_HOST   = 100
BW_ACC_SERVER = 1000
BW_CORE_SRVSW = 1000

# Topology config (mirror of traditional_campus_topo_v4.py)
# vlan_id : (human name, third octet, area)
SUBNETS = {
    10:  ("Admin-Management",    10,  1),
    20:  ("Admin-Staff",         20,  1),
    30:  ("Admin-IT",            30,  1),
    110: ("WiFi-Staff",          110, 1),
    40:  ("Academic-Lecturer",   40,  2),
    50:  ("Academic-UG-Student", 50,  2),
    60:  ("Academic-PG-Student", 60,  2),
    120: ("WiFi-Student",        120, 2),
    70:  ("Lab-Research",        70,  3),
    80:  ("Lab-Computer",        80,  3),
    90:  ("Lab-IoT",             90,  3),
}
SERVER_VLAN = 100

HOST_IP_BASE = 10


def static_host_ip(third, n):
    return f"10.10.{third}.{HOST_IP_BASE + n}"

# Server farm hosts (static IPs; gateway VIP owned by the controller)
DHCPDNS_IP    = "10.10.100.2"
WEBSRV_IP     = "10.10.100.11"
SRV1_IP       = "10.10.100.12"
SERVER_GW_VIP = "10.10.100.1"

# DHCP is owned by the controller, which leases .11, .12, ... in per subnet
# arrival order, matching the static server octets so both share one scheme.

CONTROLLER_IP   = "127.0.0.1"
CONTROLLER_PORT = 6633

# DPIDs must stay in lock step with sdn_controller_final.py.
DPIDS = {
    "core-sw1":   "0000000000000001",
    "core-sw2":   "0000000000000002",

    # ABR position area switches (SDN counterpart of area?-r-A / -r-B)
    "area1-sw-A": "000000000000001a",
    "area1-sw-B": "000000000000001b",
    "area2-sw-A": "000000000000002a",
    "area2-sw-B": "000000000000002b",
    "area3-sw-A": "000000000000003a",
    "area3-sw-B": "000000000000003b",

    # One distribution switch per area (mirrors traditional dist-swN)
    "dist-sw1":   "0000000000000011",
    "dist-sw2":   "0000000000000021",
    "dist-sw3":   "0000000000000031",

    "acc-sw100":  "0000000000000030",
    "acc-sw10":   "0000000000000110",
    "acc-sw20":   "0000000000000120",
    "acc-sw30":   "0000000000000130",
    "acc-sw110":  "0000000000000140",
    "acc-sw40":   "0000000000000210",
    "acc-sw50":   "0000000000000220",
    "acc-sw60":   "0000000000000230",
    "acc-sw120":  "0000000000000240",
    "acc-sw70":   "0000000000000310",
    "acc-sw80":   "0000000000000320",
    "acc-sw90":   "0000000000000330",
}

# area -> (A switch name, B switch name)
AREA_SW = {
    1: ("area1-sw-A", "area1-sw-B"),
    2: ("area2-sw-A", "area2-sw-B"),
    3: ("area3-sw-A", "area3-sw-B"),
}
# area -> distribution switch name (one per area)
AREA_DIST = {
    1: "dist-sw1",
    2: "dist-sw2",
    3: "dist-sw3",
}

# Default bring up timing (overridable by callers)
DEFAULT_LLDP_WAIT = 20
DEFAULT_DHCP_WAIT = 20
DHCP_TIMEOUT      = 20


# -- Helpers --

def add_sw(net, name):
    """Add an OpenFlow 1.3 OVS switch with the fixed DPID for `name`."""
    return net.addSwitch(
        name, cls=OVSSwitch,
        failMode="secure",
        protocols="OpenFlow13",
        dpid=DPIDS[name],
    )


def wait_for_real_ip(host, timeout=DHCP_TIMEOUT):
    """Poll until `host` has a real 10.10.x.x lease, then patch intf.ip."""
    intf = host.intfList()[0]
    for _ in range(timeout):
        out = host.cmd(f"ip -4 addr show {intf.name}")
        m = re.search(r"inet (10\.10\.\d+\.\d+)", out)
        if m:
            intf.ip = m.group(1)
            return m.group(1)
        time.sleep(1)
    return None


def resolve_host_ip(net, host_name):
    """Return a host's leased 10.10.x.x IP (cached or re read from kernel)."""
    h = net.get(host_name)
    intf = h.intfList()[0]
    if intf.ip and intf.ip.startswith("10.10."):
        return intf.ip
    out = h.cmd(f"ip -4 addr show {intf.name}")
    m = re.search(r"inet (10\.10\.\d+\.\d+)", out)
    if m:
        intf.ip = m.group(1)
        return m.group(1)
    return None


def write_dnsmasq_conf(path):
    """DNS only dnsmasq config. The controller does DHCP, so dnsmasq must not
    serve DHCP or the two would race to answer DISCOVERs."""
    lines = [
        "# Auto-generated by sdn_campus_topo_v6.py  (DNS ONLY -- controller does DHCP)",
        "port=53",
        "domain=campus.lk",
        "no-resolv",
        "no-hosts",
        f"address=/web.campus.lk/{WEBSRV_IP}",
        f"address=/srv1.campus.lk/{SRV1_IP}",
        f"address=/dhcpdns.campus.lk/{DHCPDNS_IP}",
        "log-facility=/tmp/dnsmasq-sdn.log",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def start_dhclient(host):
    """(Re)start a backgrounded dhclient on a host's access interface."""
    intf = host.intfList()[0].name
    host.cmd(f"ip link set {intf} up")
    host.cmd(
        f"kill $(cat /tmp/dhclient-{host.name}.pid 2>/dev/null) 2>/dev/null; true"
    )
    host.cmd(
        f"dhclient -nw -pf /tmp/dhclient-{host.name}.pid "
        f"-lf /tmp/dhclient-{host.name}.lease "
        f"{intf} > /tmp/dhclient-{host.name}.log 2>&1 &"
    )


def start_services(net, ctx):
    """Start the web server and dnsmasq (DNS only) on the server farm."""
    websrv  = ctx["websrv"]
    dhcpdns = ctx["dhcpdns"]

    info("*** Starting HTTP server on websrv\n")
    websrv.cmd("mkdir -p /tmp/www")
    websrv.cmd(
        "echo '<html><body><h1>Campus LK Web Server (SDN)</h1>"
        "<p>University of Kelaniya CT/2020/087</p></body></html>' "
        "> /tmp/www/index.html"
    )
    if "nginx" in websrv.cmd("which nginx 2>/dev/null"):
        websrv.cmd(
            "nginx -g 'daemon off;' -c /dev/stdin <<'EOF'\n"
            "events{} http{server{listen 80; root /tmp/www;"
            "access_log /tmp/nginx-access.log;}}\nEOF\n"
            "> /tmp/nginx.log 2>&1 &"
        )
    else:
        websrv.cmd(
            "cd /tmp/www && python3 -m http.server 80 "
            "> /tmp/httpserver.log 2>&1 &"
        )

    info("*** Starting dnsmasq (DNS only) on dhcpdns\n")
    dnsmasq_conf = "/tmp/dnsmasq-sdn.conf"
    write_dnsmasq_conf(dnsmasq_conf)
    dhcpdns.cmd(
        f"pkill dnsmasq 2>/dev/null; sleep 0.5; "
        f"dnsmasq -C {dnsmasq_conf} --pid-file=/tmp/dnsmasq-sdn.pid "
        "> /tmp/dnsmasq-sdn.log 2>&1 &"
    )


# -- Topology builder --

def build_topology(net, hosts_per_subnet=1):
    """Wire the SDN medium topology into `net`. Returns a context dict of
    handles the tests need. Per area shape mirrors the traditional side:
    both cores -> both area switches -> one dist switch -> access -> hosts."""
    info("*** Adding core switches\n")
    core_sw1 = add_sw(net, "core-sw1")
    core_sw2 = add_sw(net, "core-sw2")
    net.addLink(core_sw1, core_sw2, cls=TCLink, bw=BW_CORE_CORE)

    info("*** Adding area switches (ABR-position, active/active) + dist switch\n")
    area_sws = {}          # area -> (sw_a, sw_b)
    dist_sws = {}          # area -> dist_sw
    # Record area switch to core links so the failover test can cut them by handle.
    area_core_links = {}   # (area, "A"/"B", 1/2) -> Link

    for area in (1, 2, 3):
        na, nb = AREA_SW[area]
        sw_a = add_sw(net, na)
        sw_b = add_sw(net, nb)
        area_sws[area] = (sw_a, sw_b)

        # Both area switches home to both cores -> two parallel live paths.
        area_core_links[(area, "A", 1)] = net.addLink(
            sw_a, core_sw1, cls=TCLink, bw=BW_CORE_AREA)
        area_core_links[(area, "A", 2)] = net.addLink(
            sw_a, core_sw2, cls=TCLink, bw=BW_CORE_AREA)
        area_core_links[(area, "B", 1)] = net.addLink(
            sw_b, core_sw1, cls=TCLink, bw=BW_CORE_AREA)
        area_core_links[(area, "B", 2)] = net.addLink(
            sw_b, core_sw2, cls=TCLink, bw=BW_CORE_AREA)

        # One distribution switch per area, fed by both area switches.
        dist_sw = add_sw(net, AREA_DIST[area])
        dist_sws[area] = dist_sw
        net.addLink(sw_a, dist_sw, cls=TCLink, bw=BW_AREA_DIST)
        net.addLink(sw_b, dist_sw, cls=TCLink, bw=BW_AREA_DIST)

    info("*** Adding server-farm switch (dual-homed to cores)\n")
    acc_sw100 = add_sw(net, "acc-sw100")
    net.addLink(acc_sw100, core_sw1, cls=TCLink, bw=BW_CORE_SRVSW)
    net.addLink(acc_sw100, core_sw2, cls=TCLink, bw=BW_CORE_SRVSW)

    info("*** Adding server-farm hosts (static IPs)\n")
    dhcpdns = net.addHost("dhcpdns", ip=DHCPDNS_IP + "/24",
                          defaultRoute=f"via {SERVER_GW_VIP}")
    websrv  = net.addHost("websrv",  ip=WEBSRV_IP + "/24",
                          defaultRoute=f"via {SERVER_GW_VIP}")
    srv1    = net.addHost("srv1",    ip=SRV1_IP + "/24",
                          defaultRoute=f"via {SERVER_GW_VIP}")
    for h in (dhcpdns, websrv, srv1):
        net.addLink(h, acc_sw100, cls=TCLink, bw=BW_ACC_SERVER)

    info(f"*** Adding access switches + {hosts_per_subnet} host(s)/subnet\n")
    dhcp_hosts = []
    hosts_by_vlan = {}
    acc_sws = {}
    for vlan, (name, third, area) in SUBNETS.items():
        acc_sw = add_sw(net, f"acc-sw{vlan}")
        acc_sws[vlan] = acc_sw
        # One dist switch per area -> single uplink (mirrors traditional).
        net.addLink(acc_sw, dist_sws[area], cls=TCLink, bw=BW_DIST_ACC)
        vlan_hosts = []
        for n in range(1, hosts_per_subnet + 1):
            h = net.addHost(f"h{vlan}_{n}", ip="0.0.0.0")
            net.addLink(h, acc_sw, cls=TCLink, bw=BW_ACC_HOST)
            dhcp_hosts.append(h)
            vlan_hosts.append(h)
        hosts_by_vlan[vlan] = vlan_hosts

    return {
        "cores": (core_sw1, core_sw2),
        "area_sws": area_sws,
        "dist_sws": dist_sws,
        "area_core_links": area_core_links,
        "acc_sw100": acc_sw100,
        "acc_sws": acc_sws,
        "dhcpdns": dhcpdns,
        "websrv": websrv,
        "srv1": srv1,
        "dhcp_hosts": dhcp_hosts,
        "hosts_by_vlan": hosts_by_vlan,
    }


def build_network(hosts_per_subnet=1,
                  lldp_wait=DEFAULT_LLDP_WAIT,
                  dhcp_wait=DEFAULT_DHCP_WAIT):
    """Full bring up: build topology, connect to the remote Ryu controller,
    start services, wait for LLDP, run DHCP, verify leases, pre warm flows.
    The controller (sdn_controller_final.py --observe-links) must already run."""
    setLogLevel("info")
    net = Mininet(topo=None, build=False, switch=OVSSwitch,
                  controller=None, link=TCLink, autoSetMacs=True)

    info("*** Adding remote Ryu controller\n")
    c0 = net.addController("c0", controller=RemoteController,
                           ip=CONTROLLER_IP, port=CONTROLLER_PORT)

    ctx = build_topology(net, hosts_per_subnet=hosts_per_subnet)

    info("*** Building network\n")
    net.build()
    c0.start()

    info("*** Connecting switches to controller\n")
    for sw in net.switches:
        sw.start([c0])

    start_services(net, ctx)

    info(f"*** Waiting {lldp_wait}s for LLDP topology discovery to settle...\n")
    time.sleep(lldp_wait)

    sw_check = net.get("core-sw1")
    flows = sw_check.cmd("ovs-ofctl dump-flows core-sw1 -O OpenFlow13")
    n_flows = flows.count("priority=150")
    info(f"*** Controller flood rules on core-sw1: {n_flows} "
         f"(expect >0 if LLDP settled)\n")
    if n_flows == 0:
        info("*** WARNING: no flood rules yet -- waiting extra 10s\n")
        time.sleep(10)

    info("*** Starting dhclient on access hosts (fabric ready)\n")
    for h in ctx["dhcp_hosts"]:
        start_dhclient(h)

    info(f"*** Waiting {dhcp_wait}s for DHCP leases\n")
    time.sleep(dhcp_wait)

    info("*** Verifying DHCP leases\n")
    no_lease = []
    for h in ctx["dhcp_hosts"]:
        ip = wait_for_real_ip(h, timeout=10)
        if ip:
            info(f"***   {h.name}: {ip}\n")
        else:
            info(f"***   WARNING: {h.name} has no lease\n")
            no_lease.append(h)

    if no_lease:
        info(f"*** Retrying dhclient for {len(no_lease)} host(s)\n")
        for h in no_lease:
            start_dhclient(h)
        time.sleep(15)
        for h in no_lease:
            ip = wait_for_real_ip(h, timeout=8)
            info(f"***   {h.name} retry: {ip or 'STILL NO LEASE'}\n")

    # Deterministic warm start: eliminate cold L3 flows and cold host gateway ARP
    # before any measurement, so run 1 is not a first packet outlier. Warm every
    # measured host as an initiator (both directions), then gate on reachability.
    measured_hosts = [ctx["hosts_by_vlan"][v][0] for v in SUBNETS]
    measured_hosts += [ctx["websrv"], ctx["dhcpdns"], ctx["srv1"]]

    _warm_all_pairs(measured_hosts)
    _reachability_gate(measured_hosts, anchor=ctx["websrv"])

    info("*** SDN medium network ready (verified warm).\n")
    return net, ctx


def _host_ip(host):
    """Leased/static 10.10.x.x for a host, re reading the kernel if needed."""
    ip = host.IP()
    if ip and ip.startswith("10.10."):
        return ip
    return wait_for_real_ip(host, timeout=3)


def _warm_all_pairs(hosts):
    """Prime both directions of every measured pair so each host caches its
    gateway MAC and every pair's L3 flow is exercised. Untimed."""
    info(f"*** Pre-warming all pairs, both directions ({len(hosts)} hosts)\n")
    ips = {h: _host_ip(h) for h in hosts}
    for src in hosts:
        for dst in hosts:
            if src is dst:
                continue
            dst_ip = ips.get(dst)
            if dst_ip:
                src.cmd(f"ping -c 1 -W 1 {dst_ip} > /dev/null 2>&1")


def _reachability_gate(hosts, anchor, rounds=4):
    """Block until every measured host reaches `anchor` with 0% loss, or warn.
    Guarantees the network is fully warm (flows present AND host ARP primed)
    before measuring, so runs start from an identical state."""
    anchor_ip = _host_ip(anchor)
    if not anchor_ip:
        info("*** GATE WARNING: anchor has no IP; skipping reachability gate\n")
        return
    targets = [h for h in hosts if h is not anchor]
    for r in range(1, rounds + 1):
        cold = []
        for h in targets:
            out = h.cmd(f"ping -c 2 -W 1 {anchor_ip}")
            if "0% packet loss" not in out:
                cold.append(h)
        if not cold:
            info(f"*** Reachability gate PASSED on round {r} "
                 f"({len(targets)} hosts reach {anchor.name}, 0% loss)\n")
            return
        info(f"*** Gate round {r}: {len(cold)} host(s) not yet warm: "
             f"{', '.join(h.name for h in cold)} -- re-warming\n")
        for h in cold:
            hip = _host_ip(h)
            if hip:
                h.cmd(f"ping -c 1 -W 1 {anchor_ip} > /dev/null 2>&1")
                anchor.cmd(f"ping -c 1 -W 1 {hip} > /dev/null 2>&1")
        time.sleep(1)
    info(f"*** GATE WARNING: {len(cold)} host(s) still cold after {rounds} "
         f"rounds: {', '.join(h.name for h in cold)}. Do NOT trust "
         f"iteration 1 for these; investigate before measuring.\n")


def stop_network(net):
    """Best effort teardown."""
    info("*** Stopping network\n")
    try:
        net.stop()
    except Exception as e:
        info(f"*** net.stop(): {e!r} (safe to ignore after 'sudo mn -c')\n")


# -- Standalone sanity check --

def main():
    net, ctx = build_network()
    try:
        info("\n*** === Leased IPs ===\n")
        for h in ctx["dhcp_hosts"]:
            info(f"***   {h.name}: {resolve_host_ip(net, h.name)}\n")

        src, dst = net.get("h10_1"), net.get("h30_1")
        dst_ip = resolve_host_ip(net, "h30_1")
        if dst_ip:
            info(f"\n*** Sample ping h10_1 -> h30_1 ({dst_ip})\n")
            info(src.cmd(f"ping -c 3 {dst_ip}"))

        info("\n*** Dropping to Mininet CLI (Ctrl-D to exit + clean up)\n")
        CLI(net)
    finally:
        stop_network(net)


if __name__ == "__main__":
    main()
